name: ready-to-merge

on:
  pull_request:
    types:
      - ready_for_review
      - synchronize
      - edited
  pull_request_review:
    types:
      - submitted
  workflow_run:
    branches-ignore:
      - develop # default branch
      - master  # protected branch for Git-Flow
    types:
      - completed

jobs:
  triage:
    runs-on: ubuntu-18.04
    steps:
      - name: milestone check
        if: ${{github.event.milestone}} == null
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('마일스톤 입력은 필수입니다')


