name: ready-to-merge

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize
      - edited
  pull_request_review:
    types:
      - submitted
  milestone:
    types: [ opened, deleted, edited ]

jobs:
  triage:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/github-script@v3
        id: get-pr-number
        with:
          script: |
            switch (context.eventName) {
              case 'pull_request':
              case 'pull_request_review':
                return context.issue.number
              case 'workflow_run':
                if (context.payload.workflow_run.pull_requests.length !== 1) {
                  return 0
                }
                return context.payload.workflow_run.pull_requests[0].number
              default:
                throw 'invalid trigger event'
            }
          result-encoding: string

      - name: dump github milestone
        run: echo "milestone ${{toJSON(github.event.pull_request.milestone)}}"
      - name: milestone check
        if: github.event.pull_request.milestone == null
        uses: actions/github-script@v4
        with:
          script: |
            const { PULL_NUMBER } = process.env

            console.log(`owner: ${context.repo.owner}, repo: ${context.repo.repo}`)

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '마일스톤 입력은 필수입니다'
            })


